version: '2'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:8000"
    command: nginx-debug -g 'daemon off;'
    working_dir: /opt
    links:
      - php
    networks:
      - develop
    volumes:
      - ./public:/opt/public
      - ./laravel.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - php
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - develop
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'root'
  php:
    image: php:7.3.4-fpm
    container_name: php
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh install.sh
    environment:
      INSTALL_VENDOR: 'y'
      USER: "$USER"
    networks:
      - develop
    depends_on:
      - db
    links:
      - db
networks:
  develop:
    driver: bridge

volumes:
  persistent:
